### ISSUE TITLE
Function: File Name Generation

### ISSUE THREAD

**Issue by evanSpendlove** [googleinterns/step224-2020#3]
# Arguments 
id int
seed string
checksum string

# Process
Generates a filename in this format: `Hermes_<ID>_<Seed>_<Checksum>`.

# Returns
filename string

**Comment by cianbgoog** [comment]
Should this take checksum as a string? If it does, it seems to trivial to make it a separate function, since it'll be essentially 
```
func GiveMeAFileName(id int, seed, checksum string) string {
  return fmt.Sprintf("Hermes_%d_%s_%s", id, seed, string)` 
}
```

Could you maybe instead integrate it into the file generation code, so that you have a function signature something like

```
func GiveMeAFile(int id, int64 size) (string, io.LimitedReader)
```

With the `io.LimitedReader` returning the file contents?

(Obviously the function names require a little work)

**Comment by evanSpendlove** [comment]
Yes, this function is a little redundant, we can merge it with the file creation function.
